# Перечень volume
volumes:
  pg_data:

# Перечень контейнеров
services:
  # Контейнер БД
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Контейнер с бэкендом
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db

  # Контейнер с фронтендом
  frontend:
    build: ./frontend/
    env_file: .env

  # Контейнер с Nginx (gateway)
  gateway:
    build: ./gateway/
    # Проброс портов: порт 8000 хоста → порт 80 контейнера
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
